/*******************************************************************************
 *
 * FILE NAME: mainwindow.h
 *
 * DESCRIPTION:
 *  Main window class.
 *  This code was generated by qmake.
 *
 * AUTHOR: James P. Parziale
 *
 * DATE CREATED: 03/29/2010
 *
 * This file may be distributed under the terms of the GNU Public License.
 *
 *******************************************************************************
 * HISTORY:
 * 00 03/29/2010
 *   Original version
 ******************************************************************************/

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>

namespace Ui {
    class MainWindow;
}

class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

    QString GeneratePW();
    QString GeneratePatternPW();

protected:
    void changeEvent(QEvent *e);

private slots:
    void on_aboutButton_clicked();

    void on_generateButton_clicked();
    void on_clearButton_clicked();
    void on_testClearButton_clicked();
    void on_saveButton_clicked();

    void on_lowerCaseCheck_clicked();
    void on_upperCaseCheck_clicked();
    void on_numbersCheck_clicked();
    void on_specialsCheck_clicked();
    void on_patternCheck_clicked();

    void on_lengthEdit_textChanged();
    void on_totalEdit_textChanged();

    void on_testTextEdit_editingFinished();

private:
    bool InitializeValidChars(void);
    QChar PickCharacter(QString inputValidChars);

private:
    Ui::MainWindow *ui;

    bool usePattern;
    bool useNumber;
    bool useSpecial;
    bool useUpper;
    bool useLower;

    int charsPerPassword;
    int numToGenerate;

};

#endif // MAINWINDOW_H
